@echo off
:: Gradle wrapper batch script
:: Generated by GitHub Copilot on behalf of the user.

setlocal
set DIRNAME=%~dp0
set CLASSPATH=%DIRNAME%gradle\wrapper\gradle-wrapper.jar
set JAVA_CMD=
if defined JAVA_HOME (
  set JAVA_CMD=%JAVA_HOME%\bin\java.exe
) else (
  for %%i in (java.exe) do if exist "%%~$PATH:i" (set JAVA_CMD=%%~$PATH:i)
)

if not defined JAVA_CMD (
  echo Java not found on PATH or JAVA_HOME is not set. Please install Java (JDK 17+ recommended).
  exit /b 1
)

if exist "%CLASSPATH%" (
  "%JAVA_CMD%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*
  exit /b %errorlevel%
)

:: Fallback to system gradle
where gradle >nul 2>nul
if %ERRORLEVEL%==0 (
  gradle %*
  exit /b %errorlevel%
)

echo Could not find gradle wrapper jar (gradle\wrapper\gradle-wrapper.jar) and gradle was not found on PATH. Consider running 'gradle wrapper' locally or install gradle.
exit /b 1