#!/usr/bin/env sh
# Gradle wrapper script
# Launches the Gradle Wrapper jar to execute a build.
# Generated by GitHub Copilot on behalf of the user.

CLASSPATH="$(dirname "$0")/gradle/wrapper/gradle-wrapper.jar"
APP_NAME="Gradle Wrapper"
PROGNAME=$(basename $0)

default_jvm_opts="-Xmx64m"

die() {
  echo "$PROGNAME: $@" >&2
  exit 1
}

if [ -z "$JAVA_HOME" ]; then
  JAVA_CMD=$(command -v java 2>/dev/null)
else
  JAVA_CMD="$JAVA_HOME/bin/java"
fi

if [ -z "$JAVA_CMD" ]; then
  die "Java not found on PATH or JAVA_HOME is not set. Please install Java (JDK 17+ recommended)."
fi

# Run the wrapper jar if available
if [ -f "$CLASSPATH" ]; then
  exec "$JAVA_CMD" $default_jvm_opts -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
fi

# Fallback: try to use system gradle if installed
GRADLE_CMD=$(command -v gradle 2>/dev/null || true)
if [ -n "$GRADLE_CMD" ]; then
  exec "$GRADLE_CMD" "$@"
fi

die "Could not find gradle wrapper jar (gradle/wrapper/gradle-wrapper.jar) and gradle was not found on PATH. Consider running 'gradle wrapper' locally or install gradle."